compile:
	src/design.vhd

	tb/counter_bfm_pkg.vhd
	tb/counter_vvc_th.vhd
	tb/counter_vvc.vhd
	tb/td_cmd_queue_pkg.vhd
	tb/td_target_support_pkg.vhd
	tb/td_vvc_entity_support_pkg.vhd
	tb/td_vvc_framework_common_methods_pkg.vhd
	tb/testbench.vhd
	tb/vvc_cmd_pkg.vhd
	tb/vvc_methods_pkg.vhd

run:
	